<?php

namespace App\Services\AI;

use App\Jobs\ProcessAIRequest;
use App\Models\AiRequest;
use App\Models\CreditTransaction;
use App\Models\CvHistory;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Throwable;

final class AIRequestService
{
    /** @param array<string, mixed> $attributes */
    public function create(array $attributes, bool $queue = true): AiRequest
    {
        $request = AiRequest::query()->create([
            'user_id' => $attributes['user_id'],
            'cv_id' => $attributes['cv_id'] ?? null,
            'feature' => $attributes['feature'],
            'prompt' => $attributes['prompt'],
            'response' => null,
            'model' => $attributes['model'] ?? config('ai.providers.'.config('ai.default_provider').'.model'),
            'tokens_used' => 0,
            'cost' => 0,
            'status' => 'queued',
            'processing_time_ms' => null,
        ]);

        Log::info('AI request created.', $this->logContext($request));

        return $queue ? $this->queue($request) : $request;
    }

    public function queue(AiRequest $request): AiRequest
    {
        $request->forceFill(['status' => 'queued'])->save();
        ProcessAIRequest::dispatch($request->getKey());

        Log::info('AI request queued.', $this->logContext($request));

        return $request->refresh();
    }

    public function markProcessing(AiRequest $request): void
    {
        $request->forceFill(['status' => 'processing'])->save();
        Log::info('AI request processing.', $this->logContext($request));
    }

    /** @param array<string, mixed> $result */
    public function complete(AiRequest $request, array $result, int $creditsConsumed): void
    {
        $completed = DB::transaction(function () use ($request, $result, $creditsConsumed): ?AiRequest {
            $lockedRequest = AiRequest::query()->lockForUpdate()->findOrFail($request->getKey());

            if ($lockedRequest->status === 'completed') {
                return null;
            }

            $lockedRequest->forceFill([
                'response' => $result['content'],
                'provider' => $result['provider'],
                'model' => $result['model'],
                'tokens_used' => $result['total_tokens'],
                'cost' => $result['estimated_cost'],
                'processing_time_ms' => $result['processing_time'],
                'status' => 'completed',
            ])->save();

            if ($creditsConsumed > 0) {
                CreditTransaction::query()->create([
                    'user_id' => $lockedRequest->user_id,
                    'amount' => -$creditsConsumed,
                    'type' => 'ai_usage',
                    'description' => "AI request #{$lockedRequest->getKey()}: {$lockedRequest->feature}",
                ]);
            }

            if ($lockedRequest->cv_id !== null) {
                CvHistory::query()->create([
                    'cv_id' => $lockedRequest->cv_id,
                    'user_id' => $lockedRequest->user_id,
                    'action' => 'ai_'.$lockedRequest->feature,
                    'snapshot' => ['ai_request_id' => $lockedRequest->getKey(), 'response' => $result['content']],
                    'notes' => 'Generated by the AI engine.',
                ]);
            }

            return $lockedRequest;
        });

        if ($completed !== null) {
            Log::info('AI request completed.', $this->logContext($completed, [
                'provider' => $result['provider'],
                'model' => $result['model'],
                'duration' => $result['processing_time'],
                'cost' => $result['estimated_cost'],
                'tokens' => $result['total_tokens'],
                'credits' => $creditsConsumed,
            ]));
        }
    }

    public function fail(AiRequest $request, Throwable $exception): void
    {
        $failedRequest = DB::transaction(function () use ($request): ?AiRequest {
            $lockedRequest = AiRequest::query()->lockForUpdate()->find($request->getKey());

            if ($lockedRequest === null || in_array($lockedRequest->status, ['completed', 'failed'], true)) {
                return null;
            }

            $lockedRequest->forceFill(['status' => 'failed'])->save();

            return $lockedRequest;
        });

        if ($failedRequest !== null) {
            Log::error('AI request failed.', $this->logContext($failedRequest, [
                'exception' => $exception::class,
            ]));
        }
    }

    /** @param array<string, mixed> $extra
     * @return array<string, mixed>
     */
    private function logContext(AiRequest $request, array $extra = []): array
    {
        return $extra + [
            'ai_request_id' => $request->getKey(),
            'provider' => $request->provider ?? config('ai.default_provider'),
            'model' => $request->model,
            'duration' => $request->processing_time_ms,
            'cost' => $request->cost,
            'tokens' => $request->tokens_used,
            'status' => $request->status,
        ];
    }
}
